/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package prog.uni.chatapp.panels;

import java.awt.BorderLayout;
import prog.uni.chatapp.panels.controllers.ChatController;

/**
 *
 * @author Pablo
 */
public class IFChat extends javax.swing.JInternalFrame {
    private Chat chat;
    private ChatController chatController;
    
    /** Creates new form IFChat */
    public IFChat() {
        initComponents();
    }
    private void addPnl()
    {
        pnlInfo.removeAll();
        if (chat == null)
        {
            chat = new Chat();
            chatController = new ChatController(chat);
        }
        pnlInfo.add(chat, BorderLayout.CENTER);
        validate();
        repaint();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInfo = new javax.swing.JPanel();

        setMaximizable(true);
        setResizable(true);

        pnlInfo.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlInfo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlInfo;
    // End of variables declaration//GEN-END:variables

}
