/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prog.uni.chatapp.views;

import java.awt.BorderLayout;
import javax.swing.JComponent;
import javax.swing.JDialog;
import prog.uni.chatapp.panels.Chat;
import prog.uni.chatapp.panels.Login;
import prog.uni.chatapp.panels.LoginDialog;
import prog.uni.chatapp.panels.controllers.ChatController;
import prog.uni.chatapp.panels.controllers.LoginController;


/**
 *
 * @author Pablo
 */
public class ChatApp extends javax.swing.JFrame {
    private Login pnlLogin;
    private LoginController loginController;
    private ChatApp chatfr;
    private Chat chat;
    private ChatController chatController;
    private LoginDialog loginDialog;
    
    /**
     * Creates new form ChatApp
     */
    public ChatApp() {
        initComponents();
        
    }

    private void addPnlChat(boolean condition)
    {
        if (condition)
        {
            //chatfr.removeAll();
            if (chat == null)
            {
                chat = new Chat();
                chatController = new ChatController(chat);
            }
        }
        System.out.println("TODO OK");
        addComponent(chat);
    }
    
    public void flag(boolean f)
    {
        addPnlChat(f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInfo = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setSize(new java.awt.Dimension(317, 485));
        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlInfo.setLayout(new java.awt.BorderLayout());

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlInfo.add(btnLogin, java.awt.BorderLayout.LINE_START);

        getContentPane().add(pnlInfo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
         if (loginDialog == null)
        {
            loginDialog = new LoginDialog(null,true);
            loginDialog.setVisible(true);
            flag(true);
            //loginDialogController = new LoginDialogController(loginDialog);
            //pnlLogin.setVisible(true);
        }
        
        //addComponent(loginDialog);
    }//GEN-LAST:event_btnLoginActionPerformed
    private void addComponent(JComponent component) {
        pnlInfo.removeAll();
        pnlInfo.add(component, BorderLayout.CENTER);
        pnlInfo.repaint();
        this.validate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel pnlInfo;
    // End of variables declaration//GEN-END:variables
}
